accounts/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('', index_acc, name='index'),
    path('login/', auth_login, name='login'),
    path('signup/', signup, name='signup'),
    path('logout/', logoutView, name='logout')
]

buku/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'buku'
urlpatterns = [
    path('', index_buku, name='index'),
    path('JSON/<str:keyword>/', getData, name='data')
]

ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
    path('books/', include('buku.urls')),
    path('accounts/', include('accounts.urls')),
]

story6/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'story6'
urlpatterns = [
    path('', index, name='index'),
    path('add_status/', add_status, name='add_status')
]

accounts/models.py
from django.db import models

# Create your models here.

buku/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models
import datetime

# Create your models here.


class Status(models.Model):
	status = models.CharField(max_length=300)
	date = models.DateTimeField(auto_now_add=True)

story6/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
    class Meta:
        model= Status
        fields = ['status']
        labels = {
            'status':'Status',
        }
        widgets = {
            'status' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'text', 'rows' : '3'}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def index_acc(request):
	form = UserCreationForm()
	return render(request, 'acc.html', {'form' : form})

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect('/')
	else:
		form = UserCreationForm()
	return render(request, 'acc.html', {'form' : form})

def auth_login(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username , password=password)
		if user is not None:
			login(request, user)
			return redirect('/')
	return redirect('/accounts/')

@login_required
def logoutView(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            logout(request)
    return redirect('/')

buku/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import requests

response = {}
def index_buku(request):
	return render(request, 'index_buku.html')

def getData(request, keyword):
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + keyword
	json_data = json.loads(requests.get(url).text)
	return JsonResponse(json_data)

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status
# Create your views here.
def index(request):
	data = Status.objects.all()
	form = StatusForm(request.POST)
	context = {'form' : form, 'data' : data}
	return render(request, 'index.html', context)

def add_status(request):
	if request.method == 'POST':
		form = StatusForm(request.POST)
		if form.is_valid():
			form.save()
	return redirect('/')

accounts/templates/acc.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
 Accounts
{% endblock %}

{% block style %}
<style type="text/css">
  .helptext{
    font-size: 12px;
    color: grey;
  }
  ul{
    display: none;
  }

  .errorlist{
    font-size: 12px;
    display: block;
    color: red;

  }

  #accordion{
    font-family: 'Manjari', sans-serif; 
    color: white;
    margin-left: 18%;
    margin-right: 18%;
    margin-top: 2%;

  }
  .accordionHeader{
    text-align: center;
    padding-top: 1%;
    padding-bottom: 1%;
    background-color: #E0173b;
    margin-top: 2%;

  }

</style>
{% endblock %}

{% block content %}
    <div id="accordion" style="color: white">
      <h4 class="accordionHeader" id="login">LOG IN</h4>
      <div class="accordionContent">
        <form method="POST" action="{% url 'accounts:login' %}" id="form-login">
          {% csrf_token %}
            <div class="row">
              <div class="col-sm-1"><label> Username </label></div>
              <div class="col-sm-1"></div>
              <div class="col-sm-3">
                <input type="text" name="username" id="username_login" required autocomplete="off"/>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-1"><label> Password </label></div>
              <div class="col-sm-1"></div>
              <div class="col-sm-3">
                <input type="password" name="password" id="password_login" required autocomplete="off"/>
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-sm" id="login-but">Login</button><br>
        </form>
      </div>
      
      <h4 class="accordionHeader" id="signup" style="background-color: #4D34E8;">SIGN UP</h4>
      <div class="accordionContent">
        <form method="POST" action="{% url 'accounts:signup' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary btn-sm" id="signup-but">Sign Up</button>
        </form>
      </div> 
    </div>

{% endblock %}

{% block script %} 
<script src="{% static 'js/acc_scripts.js' %}"></script> 
{% endblock %}

buku/templates/index_buku.html
{% extends 'base.html' %}
{% load static %}

<!-- {% load static from staticfiles%}


<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/styleBook.css' %}" rel="stylesheet">




  </head>
  <body id="body">

    <h1 id="title-book">LETS FOUND YOUR FAVORITE BOOKS...</h1>
    <br>
  	<div class="row" style="padding-left: 5%; padding-right: 5%" id="search-box">
	    <div class="col-sm-10">
	    	<input type="text" id="keyword-box" class="form-control" maxlength="300">
	    </div>
	    <div class="col-sm-2">
	      <button id="search-button" name="search-button" class="status-button save btn btn-primary center">Search</button>
	    </div>
     </div>

     <br>
      <div class="table-responsive" id="table-book">          
      <table class="table">
        <thead class="thead-dark text-center" id="table-head">
          <tr>
            <th>NO</th>
            <th>COVER</th>
            <th>TITLE</th>
            <th>AUTHORS</th>
            <th>PUBLISHER</th>
            <th>PREVIEW</th>
          </tr>
        </thead>
        <tbody class="text-center" id="content-table">
         
        </tbody>
      </table>
      </div>
    </div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/book_script.js' %}"></script>
  </body>
</html> -->

{% block title %}
 Story 8
{% endblock %}

{% block style %} <link href="{% static 'css/styleBook.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
  <h1 id="title-book">LETS FOUND YOUR FAVORITE BOOKS...</h1>
    <br>
    <div class="row" style="padding-left: 5%; padding-right: 5%" id="search-box">
      <div class="col-sm-10">
        <input type="text" id="keyword-box" class="form-control" maxlength="300">
      </div>
      <div class="col-sm-2">
        <button id="search-button" name="search-button" class="status-button save btn btn-primary center">Search</button>
      </div>
     </div>

     <br>
      <div class="table-responsive" id="table-book">          
      <table class="table">
        <thead class="thead-dark text-center" id="table-head">
          <tr>
            <th>NO</th>
            <th>COVER</th>
            <th>TITLE</th>
            <th>AUTHORS</th>
            <th>PUBLISHER</th>
            <th>PREVIEW</th>
          </tr>
        </thead>
        <tbody class="text-center" id="content-table">
         
        </tbody>
      </table>
      </div>
    </div>
{% endblock %}

{% block script %} <script src="{% static 'js/book_script.js' %}"></script> {% endblock %}

story6/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!-- {% load static from staticfiles%}


<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">




  </head>
  <body id="body">
    <div id="button-container">
      <button id="day-theme" class="btn btn-primary" style="margin-top: 3%; margin-left: 3%"><h6>DAY MODE<h6></button>
      <button id="night-theme" class="btn btn-primary" style="margin-top: 3%; margin-left: 3%"><h6>NIGHT MODE<h6></button>
    </div>
    <div id="prof" class="container-fluid">
        <div class="row">
          <div class="col-sm-6 left" style="display: flex; justify-content: center; align-items: flex-end;"><img id="photo" src="{% static 'img/my_photo.png' %}" alt="ilma" style="max-width:80%; height: auto"></div>
          <div class="col-sm-6 right" id="basic_info" style="padding-left: 3%">
            <div class="d-flex flex-column bd-highlight mb-3">
                  <div class="p-2 bd-highlight" style="color: #FFE13C; font-family: 'Staatliches', cursive; font-size: 40px;" id="hello">HELLO,</div>
                  <div class="p-2 bd-highlight" id="my-name" style=" font-family: 'Staatliches', cursive; font-size: 40px;">I'M <span style="color:#E0173b">ILMA</span> AINUR <span style="color:#4D34E8">ROHMA</span></div>
                  <div class="p-2 bd-highlight">Jakarta, December 13, 2000</div>
                  <div class="p-2 bd-highlight">Faculty of Computer Science,<br>Universitas Indonesia</div>
                  <div class="p-2 bd-highlight">ilma.ainur81@ui.ac.id</div>
                  <div class="p-2 bd-highlight" style="margin:0px 70px 0px 0px">A lifetime learner who interested in writing world and hope to be a book’s author. As an ISTJ, i like to learn new things and enjoy working in team. As an Computer Science undergraduate student, i interested in Data Sciene, Web Development, and Software Engineering but still noob about those things.
                  </div>
              </div>
          </div>
        </div>
    </div>

    <center>
    <div id="accordion">
      <h4 class="accordionHeader">Activity</h4>
      <div class="accordionContent">eat<br>sleep<br>code<br>repeat</div>
      <h4 class="accordionHeader" style="background-color: #FFE13C; color: black">Experiences</h4>
      <div class="accordionContent"  style="background-color: #FFE13C; color: black">Staff Muslim Development Center at FUKI 2019<br>Staff Mentor and Participant at BETIS 2019<br>Staff Data Science Academy at COMPFEST 11<br>Vice Project Officer at  SIWAK NG 2019</div>
      <h4 class="accordionHeader">Achievements</h4>
       <div class="accordionContent">COMING SOON <br> AAMIIN</div>
    </div>
  </center>

  <br>
  <hr style="border-top: 4px dashed; color: blue">



    <div id="greet">
      <h2>HALO, APA KABAR?</h2>
    </div>
    <div class="form-container">
      <form method="POST" action="{% url 'story6:add_status' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1" >{{ form.status.label_tag }}</label>
            {{ form.status }}
          </div>
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </div>
          </div>
        </form>
        <hr style="border-top: 2px dashed; color: blue">
        {% for db in data %}
               <small>{{ db.date }}</small>
               <p>{{ db.status }}</p>
               <hr style="border-top: 2px dashed; color: blue">
        {% endfor %}
    </div>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    
  </body>
</html> -->

{% block title %}
 Story 6 & 7
{% endblock %}

{% block style %} <link href="{% static 'css/styles.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
  <div id="button-container">
      <button id="day-theme" class="btn btn-primary" style="margin-top: 3%; margin-left: 3%"><h6>DAY MODE<h6></button>
      <button id="night-theme" class="btn btn-primary" style="margin-top: 3%; margin-left: 3%"><h6>NIGHT MODE<h6></button>
    </div>
    <div id="prof" class="container-fluid">
        <div class="row">
          <div class="col-sm-6 left" style="display: flex; justify-content: center; align-items: flex-end;"><img id="photo" src="{% static 'img/my_photo.png' %}" alt="ilma" style="max-width:80%; height: auto"></div>
          <div class="col-sm-6 right" id="basic_info" style="padding-left: 3%">
            <div class="d-flex flex-column bd-highlight mb-3">
                  <div class="p-2 bd-highlight" style="color: #FFE13C; font-family: 'Staatliches', cursive; font-size: 40px;" id="hello">HELLO,</div>
                  <div class="p-2 bd-highlight" id="my-name" style=" font-family: 'Staatliches', cursive; font-size: 40px;">I'M <span style="color:#E0173b">ILMA</span> AINUR <span style="color:#4D34E8">ROHMA</span></div>
                  <div class="p-2 bd-highlight">Jakarta, December 13, 2000</div>
                  <div class="p-2 bd-highlight">Faculty of Computer Science,<br>Universitas Indonesia</div>
                  <div class="p-2 bd-highlight">ilma.ainur81@ui.ac.id</div>
                  <div class="p-2 bd-highlight" style="margin:0px 70px 0px 0px">A lifetime learner who interested in writing world and hope to be a book’s author. As an ISTJ, i like to learn new things and enjoy working in team. As an Computer Science undergraduate student, i interested in Data Sciene, Web Development, and Software Engineering but still noob about those things.
                  </div>
              </div>
          </div>
        </div>
    </div>

    <center>
    <div id="accordion">
      <h4 class="accordionHeader">Activity</h4>
      <div class="accordionContent">eat<br>sleep<br>code<br>repeat</div>
      <h4 class="accordionHeader" style="background-color: #FFE13C; color: black">Experiences</h4>
      <div class="accordionContent"  style="background-color: #FFE13C; color: black">Staff Muslim Development Center at FUKI 2019<br>Staff Mentor and Participant at BETIS 2019<br>Staff Data Science Academy at COMPFEST 11<br>Vice Project Officer at  SIWAK NG 2019</div>
      <h4 class="accordionHeader">Achievements</h4>
       <div class="accordionContent">COMING SOON <br> AAMIIN</div>
    </div>
  </center>

  <br>
  <hr style="border-top: 4px dashed; color: blue">

  <div id="status-section">
    <div id="greet">
      <h2>HALO, APA KABAR?</h2>
    </div>
    <div class="form-container">
      <form method="POST" action="{% url 'story6:add_status' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1" >{{ form.status.label_tag }}</label>
            {{ form.status }}
          </div>
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </div>
          </div>
        </form>
        <hr style="border-top: 2px dashed; color: blue">
        {% for db in data %}
               <small>{{ db.date }}</small>
               <p>{{ db.status }}</p>
               <hr style="border-top: 2px dashed; color: blue">
        {% endfor %}
    </div>
  </div>
{% endblock %}

{% block script %} <script src="{% static 'js/script.js' %}"></script> {% endblock %}

templates/base.html
<!DOCTYPE html> 
<html style="scroll-behavior: smooth;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>{% block title %}{% endblock %}</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block style %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </head>
  <body id="body" style="background-color: black">
  	<div style="font-family: 'Manjari', sans-serif;"> 
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">NEW STORY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="#status-section">Status</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/books">Books</a>
            </li>
            <li class="nav-item">
              {% if user.is_authenticated %}
                <a class="nav-link" href="/accounts/logout" id="logout-button">Logout</a>
              {% else %}
                <a class="nav-link" href="/accounts">Login</a>
              {% endif %}
            </li>
          </ul>
          <span class="navbar-text">
            {% if user.is_authenticated %}
              <h6> <b> Welcome {{ request.user.username }}! </b></h6>
            {% else %}
              <h6><b> Welcome to my website, login for free!</b></h6>
            {% endif %}
          </span>
        </div>
      </nav>
      <br><br><br>
    </div>
  	{% block content %} {% endblock %}

  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    {% block script %} {% endblock %}
  </body>